server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service            #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
            - After=2024-03-13T16:52:08.271304500+08:00[Asia/Shanghai]   #该时间之后才能访问
            #- Before=2024-03-13T16:52:08.271304500+08:00[Asia/Shanghai]   #该时间之前才能访问
            #- Between=2024-03-13T16:52:08.271304500+08:00[Asia/Shanghai],2024-03-13T16:58:08.271304500+08:00[Asia/Shanghai]   #该时间之间才能访问
            #- Cookie=username,xxx
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Host=**.atguigu.com  #curl http://localhost:9527/pay/gateway/get/3 -H  "Host:www.atguigu.com"
            #- Query=username, \d+  # 要有参数名username并且值还要是整数才能路由    #http://localhost:9527/pay/gateway/get/3?username=123
            #- Method=GET  #只能用get访问


        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service            #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由

        - id: pay_routh3 #pay_routh3
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
              - Path=/pay/gateway/filter/**              # 断言，路径相匹配的进行路由
          filters:
              - AddRequestHeader=X-Request-atguigu1,atguiguValue1  # 请求头kv，若一头含有多参则重写一行设置
              - AddRequestHeader=X-Request-atguigu2,atguiguValue2